### ISSUE TITLE
system-config.js not present

### ISSUE THREAD

**Issue by designcourse** [Codenator81/ng2do-mean-app#4]
I followed the whole guide but once it came time to paste in some lines in system-config.js, didn't work because it's not there after ng new.  I assume this is because they switched to karma?  

What steps would I take to get this working now, based on your guide?  Thanks.

**Comment by Codenator81** [comment]
@designcourse  Then switch to webpack instead of systemJs.  But then there more easy to use Universal in it. 
@gh0st migrate this project to webpack so check last code
readme outdated now
Main difference now you need files like https://github.com/Codenator81/ng2do-mean-app/blob/master/public/vendor/my-app/src/polyfills.ts for webpack find dependecies

Hope help you little bit

**Comment by Codenator81** [comment]
Don`t forget ng cli still beta. There can be major changes
I will update guide when them release ng-cli
For now it is just waste of time

**Comment by Codenator81** [comment]
@designcourse  Updated entire app. Guide updated too
